from . import product
from . import stock_warehouse
from . import stock_location
from . import stock_move
from . import stock_quant
from . import stock_picking
from . import stock_contract
from . import stock_vehicle
from . import res_company
